/***********************************************************************/
/*                                                                     */
/*  FILE        :Empty.c                                               */
/*  DATE        :Mon, Jan 08, 2007                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.0).     */
/*                                                                     */
/***********************************************************************/
     
#include "qsk_bsp.h"
#include "qsk_led.h"
#include "qsk_switch.h"


// prototypes

void mcu_init(void);	              

/* *******************************************************************
 Description:
 Entry:
 Returns:
 Notes:
 
***********************************************************************/ 
void main(void)
{
	int a = 0, b = 0, c = 0;
	
	mcu_init();
	InitLED();
	InitSwitch();
	
	while(1) {
		if( !p8_3 || a == 1 ) {
			a = 1;
			if( p8_3 ) {
				p8_0 = !p8_0;
				a = 0;
			}
		}
		
		if( !p8_2 || b == 1 ) {
			b = 1;
			if( p8_2 ) {
				p7_4 = !p7_4;
				b = 0;
			}
		}
		
		if( !p8_1 || c == 1 ) {
			c = 1;
			if( p8_1 ) {
				p7_2 = !p7_2;
				c = 0;
			}
		}
	}
}
